name: Deploy PR Preview

run-name: Deploying preview for "${{ github.ref }}" by ${{ github.actor }} 🚀

#! WARN: any edit to this file should be done too to: learn-qci/.github/workflows/deploy.yml

on:
  pull_request:
    branches:
      - main

jobs:
  checkout_codebase:
    runs-on: ubuntu-latest

    steps:
      # End Output URL
      - name: Checkout QCI learn
        uses: actions/checkout@v4
        with:
          repository: qci-enablement/learn-qci
          ref: main
          token: ${{ secrets.P_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            apps/learn/.next/cache
            bin
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile # optional, --immutable
      - name: Add Loading
        env:
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          DESC_STATE: loading
        run: node ./.github/workflows/update-description.js
      - name: ESlint
        run: yarn learn lint
      - name: Cache Data
        id: syncData
        uses: actions/cache@v4
        with:
          path: apps/learn/build/data # Path to the binary file
          key: ${{ runner.os }}-data-${{ hashFiles('**/contentful-data.json', '**/metadata.json') }}
      - name: Sync data
        run: yarn learn sync-data
        env:
          DEV_ENV: pr
          QCI_DATA_BRANCH_PR: ${{ github.ref_name }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
          CONTENTFUL_TOKEN_PROD: ${{ secrets.CONTENTFUL_TOKEN_PROD }}
      - name: Cache Pandoc Binay
        id: binaycache
        uses: actions/cache@v4
        with:
          path: bin # Path to the binary file
          key: ${{ runner.os }}-binary-${{ hashFiles('bin/**/*') }}
      - name: Install Pandoc
        if: steps.binaycache.outputs.cache-hit != 'true'
        run: bash ./scripts/install-pandoc.sh
      - name: Build website
        run: yarn learn next build
      # Deploy PR Preview
      - name: Deploy PR Preview to Netlify
        id: netlify-pr-preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=apps/learn/dist --filter=@quantumcomputinginc/learn --functions=netlify/functions --alias=data-preview-${{ github.event.number }} --message="PR Preview ${{ github.event.number }} By ${{ github.actor }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      # Detect changed files
      - name: List changes to generate URLs
        id: list_changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          owner=${{ github.repository_owner }}
          repo=$(echo ${{ github.repository }} | cut -d'/' -f2)
          files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$owner/$repo/pulls/$pr_number/files" \
            | jq -r '.[] | select(.status == "added" or .status == "modified") | .filename' | paste -sd ",")
          echo "PREVIEW_URLS=$files" >> $GITHUB_ENV
      # End Output URL
      - name: Add deploy preview URL
        env:
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          PR_TYPE: data
        run: node ./.github/workflows/update-description.js
